version: '3.6'
services:
  mongodb:
    image: mongo:4.2.3-bionic
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - app-network
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./mongo/mongodb:/data/db
      - ./mongo/mongoconfig:/data/configdb

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - '2000:2000'
    networks:
      - app-network
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - MONGO_DB_NAME=auth
      - AUTH_PORT=2000
      - AUTH_KEY=qwerty

  todo:
    build:
      context: ./todo
      dockerfile: Dockerfile
    container_name: todo
    ports:
      - '2001:2001'
    networks:
      - app-network
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - MONGO_DB_NAME=auth
      - TODO_PORT=2001
      - AUTH_KEY=qwerty

networks:
  app-network:
    driver: bridge

volumes:
  mongodb:
  mongoconfig:


