version: '3.6'
services:
  mongodb:
    image: mongo:4.2.8
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    
volumes:
  mongodb:
  mongoconfig:

